version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping depolyment package..."
  post_build:
    commands:
      - echo "Updating lambda functions..."
      - aws lambda update-function-code --function-name image_search.py
      - aws lambda update-function-code --function-name image-index.py
      - echo "Done"
